USE eco;

ALTER TABLE users
MODIFY COLUMN last_name VARCHAR(50) NULL,
MODIFY COLUMN number VARCHAR(11) NULL,
MODIFY COLUMN address VARCHAR(255) NULL,
MODIFY COLUMN city VARCHAR(85) NULL,
MODIFY COLUMN country VARCHAR(56) NULL,
MODIFY COLUMN rol_id INT(11) NOT NULL DEFAULT 2;
